[build]
  functions = "./functions"
  publish = "."


[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/github"
  status = 200
  force = true


[[redirects]]
  from = "/api/files"
  to = "/.netlify/functions/files"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/logout"
  to = "/logout.html"
  status = 200
  force = true
